# Generated by Django 6.0.1 on 2026-03-11 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician_signup',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='technician_signup',
            name='service_category',
            field=models.CharField(blank=True, choices=[('AC Service', 'AC Service'), ('Electrician', 'Electrician'), ('Washing Machine Service', 'Washing Machine Service'), ('Plumbing', 'Plumbing')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='technician_signup',
            name='working_locations',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='technician_signup',
            name='years_of_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
