# Generated by Django 6.0.1 on 2026-03-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_technician_signup_profile_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending - No Technician Assigned'), ('Assigned', 'Assigned - Technician Assigned'), ('In Progress', 'In Progress - Work Started'), ('Completed', 'Completed - Work Done')], default='Pending', max_length=20),
        ),
    ]
