# Generated by Django 6.0.4 on 2026-04-30 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_service'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='service',
            table='Service',
        ),
    ]
