# Generated by Django 6.0.4 on 2026-05-15 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_service_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicerequest')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.technician_signup')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
