# Generated by Django 6.0.4 on 2026-05-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_techniciannotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='tracking_active',
            field=models.BooleanField(default=False),
        ),
    ]
