# Generated by Django 6.0.4 on 2026-05-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_servicerequest_tracking_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='customer_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='customer_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
