# Generated by Django 6.0.4 on 2026-05-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_servicerequest_amount_servicerequest_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_signup',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer_signup',
            name='verification_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
