# Generated by Django 5.2.7 on 2026-08-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_customer_signup_id_alter_service_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='service_request_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
