# Generated by Django 5.2.7 on 2026-08-24 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_customer_signup_wallet_balance_wallettransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_score', models.FloatField()),
                ('reason', models.CharField(max_length=255)),
                ('impression_count', models.IntegerField(default=1)),
                ('clicked', models.BooleanField(default=False)),
                ('booked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_logs', to='core.customer_signup')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service')),
            ],
            options={
                'db_table': 'RecommendationLog',
                'ordering': ['-created_at'],
            },
        ),
    ]
