# Generated by Django 5.2.7 on 2026-08-24 17:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_recommendationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_signup',
            name='last_offer_popup_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FLAT', 'Flat Amount')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maximum_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('minimum_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('target_segment', models.CharField(choices=[('ALL', 'All Customers'), ('NEW_CUSTOMER', 'New Customers (Welcome)'), ('INACTIVE', 'Inactive Customers (Re-engagement)'), ('FREQUENT', 'Frequent Customers')], default='ALL', max_length=50)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('usage_limit', models.IntegerField(default=1, help_text='How many times the offer can be used in total globally')),
                ('per_customer_limit', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicable_service', models.ForeignKey(blank=True, help_text='Leave blank for all services', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.service')),
            ],
            options={
                'db_table': 'Offer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('shown_at', models.DateTimeField(blank=True, null=True)),
                ('redeemed', models.BooleanField(default=False)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('is_welcome_offer', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_offers', to='core.customer_signup')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.offer')),
            ],
            options={
                'db_table': 'CustomerOffer',
                'unique_together': {('customer', 'offer')},
            },
        ),
    ]
