# Generated by Django 5.2.7 on 2026-08-24 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_customer_signup_last_offer_popup_at_offer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_signup',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customer_signup',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_referrals', to='core.customer_signup'),
        ),
        migrations.CreateModel(
            name='ReferralLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_by', to='core.customer_signup')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards_earned', to='core.customer_signup')),
            ],
            options={
                'db_table': 'ReferralLog',
            },
        ),
    ]
