# Generated by Django 5.2.7 on 2026-08-24 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_customer_signup_referral_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendationlog',
            name='impression_count',
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='booked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='clicked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='shown_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 8, 24, 19, 29, 50, 981064, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
