# Generated by Django 5.2.7 on 2026-08-24 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_recommendationlog_impression_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Platform Analytics',
                'managed': False,
            },
        ),
        migrations.RenameField(
            model_name='customeroffer',
            old_name='shown_at',
            new_name='viewed_at',
        ),
        migrations.AddField(
            model_name='customeroffer',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='applied_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='core.offer'),
        ),
        migrations.AlterField(
            model_name='customeroffer',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='core.customer_signup'),
        ),
        migrations.AlterField(
            model_name='customeroffer',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_assignments', to='core.offer'),
        ),
    ]
