# Generated by Django 5.2.7 on 2026-08-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_platformanalytics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician_signup',
            name='service_category',
            field=models.CharField(blank=True, choices=[('AC Repair', 'AC Repair'), ('Electrical', 'Electrical'), ('Plumbing', 'Plumbing'), ('Cleaning', 'Cleaning')], max_length=100, null=True),
        ),
    ]
