# Generated by Django 5.2.7 on 2026-08-30 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_technician_signup_service_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_points', models.DecimalField(decimal_places=1, default=1.0, max_digits=3)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.servicerequest')),
                ('support_ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.supportticket')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='core.technician_signup')),
            ],
            options={
                'db_table': 'TechnicianWarning',
            },
        ),
        migrations.CreateModel(
            name='TechnicianRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer_signup')),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating_record', to='core.servicerequest')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core.technician_signup')),
            ],
            options={
                'db_table': 'TechnicianRating',
                'unique_together': {('customer', 'service_request')},
            },
        ),
    ]
