# Generated by Django 5.2.7 on 2026-09-10 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_servicerequest_technician_live_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='technician_signup',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='TechnicianIncentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('incentive_type', models.CharField(choices=[('FIVE_STAR_BONUS', '5-Star Rating Reward'), ('MISSION_COMPLETION', 'Mission / Milestone Bonus'), ('WEEKLY_TOP_PERFORMER', 'Weekly Top Performer'), ('OTHER', 'Special Reward')], default='MISSION_COMPLETION', max_length=50)),
                ('status', models.CharField(choices=[('EARNED', 'Earned'), ('CREDITED', 'Credited to Wallet'), ('PENDING_APPROVAL', 'Pending Approval')], default='CREDITED', max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentives', to='core.technician_signup')),
            ],
            options={
                'db_table': 'TechnicianIncentive',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TechnicianSupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('category', models.CharField(choices=[('PAYMENT_EARNINGS', 'Payment / Earnings'), ('SERVICE_BOOKING', 'Service / Booking'), ('WALLET_WITHDRAWAL', 'Wallet / Withdrawal'), ('INCENTIVE_REWARD', 'Incentive / Reward'), ('APP_TECHNICAL', 'App / Technical Issue'), ('ACCOUNT_PROFILE', 'Account / Profile'), ('OTHER', 'Other')], max_length=50)),
                ('issue', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20)),
                ('guided_flow_state', models.JSONField(blank=True, default=list)),
                ('escalation_reason', models.TextField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('escalated_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_technician_tickets', to=settings.AUTH_USER_MODEL)),
                ('related_incentive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='core.technicianincentive')),
                ('related_service_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technician_support_tickets', to='core.servicerequest')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='core.technician_signup')),
            ],
            options={
                'db_table': 'TechnicianSupportTicket',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TechnicianSupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_role', models.CharField(choices=[('TECHNICIAN', 'Technician'), ('ADMIN', 'Admin'), ('SYSTEM', 'System')], default='TECHNICIAN', max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.techniciansupportticket')),
            ],
            options={
                'db_table': 'TechnicianSupportMessage',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TechnicianWalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technician_transactions', to='core.servicerequest')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to='core.technician_signup')),
            ],
            options={
                'db_table': 'TechnicianWalletTransaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='techniciansupportticket',
            name='related_wallet_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='core.technicianwallettransaction'),
        ),
        migrations.CreateModel(
            name='TechnicianWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payout_method', models.CharField(default='Bank Transfer', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='core.technician_signup')),
            ],
            options={
                'db_table': 'TechnicianWithdrawal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='techniciansupportticket',
            name='related_withdrawal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='core.technicianwithdrawal'),
        ),
    ]
